#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : iso8601
Version  : 1.0.0
Release  : 64
URL      : https://files.pythonhosted.org/packages/f9/bd/425a807d88c83768f282010a65031223f37c41e7f485bdd92ba00d1832e1/iso8601-1.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/f9/bd/425a807d88c83768f282010a65031223f37c41e7f485bdd92ba00d1832e1/iso8601-1.0.0.tar.gz
Summary  : Simple module to parse ISO 8601 dates
Group    : Development/Tools
License  : MIT
Requires: iso8601-license = %{version}-%{release}
Requires: iso8601-python = %{version}-%{release}
Requires: iso8601-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : py
BuildRequires : pytest

%description
Simple module to parse ISO 8601 dates
This module parses the most common forms of ISO 8601 date strings (e.g. 2007-01-14T20:34:22+00:00) into datetime objects.

%package license
Summary: license components for the iso8601 package.
Group: Default

%description license
license components for the iso8601 package.


%package python
Summary: python components for the iso8601 package.
Group: Default
Requires: iso8601-python3 = %{version}-%{release}

%description python
python components for the iso8601 package.


%package python3
Summary: python3 components for the iso8601 package.
Group: Default
Requires: python3-core
Provides: pypi(iso8601)

%description python3
python3 components for the iso8601 package.


%prep
%setup -q -n iso8601-1.0.0
cd %{_builddir}/iso8601-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1636411842
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/iso8601
cp %{_builddir}/iso8601-1.0.0/LICENSE %{buildroot}/usr/share/package-licenses/iso8601/604d3444602058d69df81bd0c30c6944517360db
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/iso8601/604d3444602058d69df81bd0c30c6944517360db

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
